#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ScitptFile=setup-ezstorage.sh
EZRomsDir=$SCRIPT_DIR/EZStorage_all

WriteHeader() {
    cat <<EOF >"$ScitptFile"
#!/bin/bash
# This script is auto-generated by make-setup-ezstorage.sh
# Do not edit this file directly.
OS=\$1
OSRomsDir=\$2
EZRomsDir=\$3

[[ -z "\$OS" || -z "\$OSRomsDir" || -z "\$EZRomsDir" ]] &&  exit 1

EOF
}

WriteIfThen() {
    local os="$1"
    cat <<EOF >>"$ScitptFile"
if [[ "\$1" = "$os" ]]
then
EOF
}

WriteBind() {
    local EZRomDir="\$EZRomsDir/$1"
    local OSRomDir="\$OSRomsDir/$2"
    cat <<EOF >>"$ScitptFile"

    [[ ! -d "$EZRomDir" ]] && mkdir -p "$EZRomDir"
    [[ ! -d "$OSRomDir" ]] && mkdir -p "$OSRomDir"
    mount --bind "$EZRomDir" "$OSRomDir"

EOF
}

WriteFi() {
    cat <<EOF >>"$ScitptFile"
fi

EOF
}



WriteHeader

#process mapped binds
for maptype in Music Video
do
    for EZRomDir in $(find "$EZRomsDir" -type f -name "DO_NOT_USE.MappedTo-00_$maptype" -exec dirname {} \;)
    do
        WriteBind "00_$maptype" "$(basename $EZRomDir)"
    done
done